api/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import *

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'featured', FeaturedInsertionViewSet, basename='featured')
router.register(r'search', InsertionViewSet, basename='search')
router.register(r'location/autocomplete', LocationAutocompleteViewSet, basename='location-autocomplete')
router.register(r'reserve', ReservationViewSet, basename='reserve')
router.register(r'review', LeaveReviewViewSet, basename='leave-review')
router.register(r'account/picture', AccountEditPicViewSet, basename='account-edit-picture')
router.register(r'account/reservation/delete', ReservationDeleteViewSet, basename='reservation-delete')
router.register(r'account/booking/delete', BookingDeleteViewSet, basename='booking-delete')

urlpatterns = router.urls

progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from progetto import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('insertion/', include('insertion.urls', namespace='insertion')),
    path('api/', include('api.urls')),
    path('', include('user.urls', namespace='user')),
    path("__reload__/", include("django_browser_reload.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path(r'login', views.login_view, name='login'),
    path(r'signup', views.signup_view, name='signup'),
    path(r'logout', views.logout_view, name='logout'),
    path(r'account', views.account_view, name='profile'),
    path(r'account/changepassword', auth_views.PasswordResetView.as_view(), name='changepassword'),
    path(r'account/bookings', views.bookings_view, name='bookings'),
    path(r'account/newinsertion', views.add_room_view, name='newinsertion'),
    path(r'account/insertions', views.my_insertions_view, name='myinsertions'),
    path(r'account/insertion/<str:uuid>', views.edit_insertion_view, name='editinsertion'),
    path(r'account/editpayment', views.payment_settings_view, name='paymentsettings'),
    path(r'account/reservations', views.reservations_view, name='reservations'),
]


theme/templates/layouts/account.html
{% extends "layouts/base.html" %}
{% block title %}Account{% endblock %} 
{% load custom_tags %}
{% block tags %}
{% endblock %}
{% block content %}
<div class="w-full flex flex-col min-h-lvh">
    <div class="flex flex-row flex-wrap">
        <div class="min-w-[300px] shadow-2xl p-10 max-lg:flex-1 rounded-xl m-10 h-fit">
            <h4 class="text-lg font-bold p-4">Account</h4>
            <div class="border-b-2 rounded-md"></div>
            <div class="account__nav_items flex flex-col">
                <a href="{% url 'user:profile' %}" class="{% url_active 'user:profile' %} p-4 flex items-center gap-2 "><ion-icon name="person-outline" ></ion-icon> Il tuo profilo</a>
                <a href="{% url 'user:bookings' %}" class="{% url_active 'user:bookings' %} p-4 flex items-center gap-2"><ion-icon name="home-outline" ></ion-icon> I tuoi soggiorni</a>
                <a href="{% url 'user:changepassword' %}" class="{% url_active 'user:changepassword' %} p-4 flex items-center gap-2"><ion-icon name="key-outline" ></ion-icon>Cambia password</a>
                <a href="{% url 'user:logout' %}" class="p-4 text-red-400 flex items-center gap-2"><ion-icon name="exit-outline" ></ion-icon>Esci</a>
            </div>
            {% if request.user.role == 'HOST' %}
            <h4 class="text-lg font-bold p-4">Impostazioni Host</h4>
            <div class="border-b-2 rounded-md"></div>
            <div class="account__nav_items flex flex-col">
                <a href="{% url 'user:myinsertions' %}" class="{% url_active 'user:myinsertions' %} p-4 flex items-center gap-2"><ion-icon name="home-outline" ></ion-icon> I tuoi immobili</a>
                <a href="{% url 'user:reservations' %}" class="{% url_active 'user:reservations' %} p-4 flex items-center gap-2"><ion-icon name="home-outline" ></ion-icon> Gestisci prenotazioni</a>
                <a href="{% url 'user:paymentsettings' %}" class="{% url_active 'user:paymentsettings' %} p-4 flex items-center gap-2"><ion-icon name="cash-outline" ></ion-icon> Pagamento</a>
                <a href="{% url 'user:newinsertion' %}" class="{% url_active 'user:newinsertion' %} p-4 flex items-center gap-2"><ion-icon name="add-outline" ></ion-icon> Aggiungi un immobile</a>
            </div>
            {% endif %}
        </div>
        <div class="p-8 flex-grow ">
            {% block content1 %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    const profilePic = document.querySelector('#open_pic_modal');
    const picModal = document.querySelector('.pic__modal');
    const modalClose = document.querySelector('.modal__close');

    profilePic.addEventListener('click', () => {
        picModal.classList.remove('hidden');
    });

    modalClose.addEventListener('click', () => {
        picModal.classList.add('hidden');
    });

    $('#change_pic_form').submit(function(e) {
        e.preventDefault();
        const formData = new FormData(this);
        $.ajax({
            type: 'POST',
            url: '/api/account/picture/',
            data: formData,
            processData: false,
            contentType: false,
            success: function(response) {
                location.reload();
            },
            error: function(error) {
                $('#error_modal_message').text(error.responseJSON.error);
            }
        });
    });

</script>
{% endblock %}

theme/templates/layouts/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0 minimal-ui"/>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v3.5.1/mapbox-gl.css" rel="stylesheet">
    {% block tag %}{% endblock tag %}
    <style>
        body {
            font-family: "Nunito", sans-serif;
        }
    </style>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <title>Airbnb - {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'partials/header.html' %}
    <div class="w-full min-h-svh">
      {% block content %}
      {% endblock content %} 
    </div>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.13.3/jquery-ui.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    {% block scripts %}{% endblock scripts %}
    {% include 'partials/footer.html' %}
  </body>
</html>